CREATE TABLE IF NOT EXISTS learning_topics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  archived INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS learning_sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  topic_id INTEGER NOT NULL REFERENCES learning_topics(id),
  started_at DATETIME NOT NULL,
  ended_at DATETIME,
  duration INTEGER DEFAULT 0,
  last_active_at DATETIME NOT NULL
);
