CREATE TABLE IF NOT EXISTS calendar_overrides (
  date VARCHAR(10) PRIMARY KEY,
  status VARCHAR(20),
  topic TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
