/**
 * Canonical Performance Mentor & Time-Off Intelligence Service
 * 
 * Central source of truth for:
 * 1. Earned Free-Day Capacity:
 *    - 6.0h/day period ideal is the locked baseline (never 8.0h/day).
 *    - idealHours = calendarDays * 6.0
 *    - surplusHours = max(0, actualHours - idealHours)
 *    - earnedFreeDays = floor(surplusHours / 6.0)
 *    - Fractional surplus is never counted as a full free day.
 * 2. Time-Off Simulation:
 *    - Non-mutating forward projection: "What happens if I take X days off?"
 *    - Calculates before/after averages, status transitions, remaining surplus, and resulting deficit.
 * 3. Recovery Intelligence:
 *    - Deficits calculate required recovery pace within period.
 *    - Enforces 10.0h/day planning ceiling (never recommends > 10.0h/day).
 *    - Projects extended recovery horizon at +4.0h/day surplus rate (10.0h max - 6.0h baseline).
 * 4. Separation of Concepts:
 *    - Earned free days only generated by positive surplus.
 *    - Deficits never generate free days; recovery days are never called free days.
 * 5. Weekly & Monthly Independence:
 *    - Evaluates weekly (7 days, 42h) and monthly (daysInMonth, daysInMonth * 6h) independently.
 */

import {
  APP_TIMEZONE,
  formatDateInTimezone,
  getTodayDateString,
  getISOWeekAndYear,
  getReportingWeek,
  getCurrentMonthRange,
} from "./dates";
import {
  SessionRecordInput,
  calculateSessionPerformance,
  getInclusiveDayCount,
} from "./performance";
import {
  calculatePerformanceMentor,
  PerformanceMentorOverview,
} from "./performanceMentorCore";

export * from "./performanceMentorCore";

/**
 * Live canonical mentor overview query.
 * Gathers hunting and learning sessions and compiles independent Weekly and Monthly mentor intelligence.
 */
export async function getPerformanceMentorOverview(options?: {
  timezone?: string;
  simulateWeeklyDaysOff?: number;
  simulateMonthlyDaysOff?: number;
  workSecondsByDate?: Record<string, number>;
  workHoursByDate?: Record<string, number>;
  huntingSessions?: SessionRecordInput[];
  learningSessions?: SessionRecordInput[];
  allSessions?: SessionRecordInput[];
}): Promise<PerformanceMentorOverview> {
  const tz = options?.timezone || APP_TIMEZONE;
  const todayStr = getTodayDateString(tz);

  // 1. Current Week
  const weekInfo = getISOWeekAndYear(todayStr, tz);
  const weekRange = getReportingWeek(weekInfo.year, weekInfo.week, tz);
  const weekTotalDays = getInclusiveDayCount(weekRange.startStr, weekRange.endStr); // 7
  let weekElapsedDays = 0;
  if (todayStr < weekRange.startStr) weekElapsedDays = 0;
  else if (todayStr > weekRange.endStr) weekElapsedDays = weekTotalDays;
  else weekElapsedDays = getInclusiveDayCount(weekRange.startStr, todayStr);

  const weekRemainingDays = Math.max(0, weekTotalDays - weekElapsedDays);

  // 2. Current Month
  const monthRange = getCurrentMonthRange(todayStr, tz);
  const monthTotalDays = monthRange.daysInMonth;
  let monthElapsedDays = 0;
  if (todayStr < monthRange.startStr) monthElapsedDays = 0;
  else if (todayStr > monthRange.endStr) monthElapsedDays = monthTotalDays;
  else monthElapsedDays = getInclusiveDayCount(monthRange.startStr, todayStr);

  const monthRemainingDays = Math.max(0, monthTotalDays - monthElapsedDays);

  // Determine work hours source
  let getWorkHoursForDate: (d: string) => number;

  if (options?.workHoursByDate) {
    getWorkHoursForDate = (d: string) => options.workHoursByDate![d] || 0;
  } else if (options?.workSecondsByDate) {
    getWorkHoursForDate = (d: string) =>
      Math.round(((options.workSecondsByDate![d] || 0) / 3600) * 100) / 100;
  } else if (options?.huntingSessions || options?.learningSessions || options?.allSessions) {
    // Backward compatibility for unit tests passing synthetic sessions
    const hunting = options.huntingSessions || [];
    const learning = options.learningSessions || [];
    const all = options.allSessions || [];
    getWorkHoursForDate = (d: string) => {
      if (all.length > 0) {
        const filtered = all.filter((s) => s.started_at && formatDateInTimezone(s.started_at, tz) === d);
        return calculateSessionPerformance({ allSessions: filtered }, 1, tz).totalProductiveHours;
      }
      const h = hunting.filter((s) => s.started_at && formatDateInTimezone(s.started_at, tz) === d);
      const l = learning.filter((s) => s.started_at && formatDateInTimezone(s.started_at, tz) === d);
      return calculateSessionPerformance({ huntingSessions: h, learningSessions: l }, 1, tz).totalProductiveHours;
    };
  } else {
    // Canonical database source: work_time_daily
    const { getWorkTimeBetweenDates } = await import("@/lib/repositories/workTimeDaily");
    const earliestDate = weekRange.startStr < monthRange.startStr ? weekRange.startStr : monthRange.startStr;
    const latestDate = weekRange.endStr > monthRange.endStr ? weekRange.endStr : monthRange.endStr;
    const workSecondsMap = await getWorkTimeBetweenDates(earliestDate, latestDate);
    getWorkHoursForDate = (d: string) =>
      Math.round(((workSecondsMap[d] || 0) / 3600) * 100) / 100;
  }

  // Calculate actual hours for week
  let weekActualHours = 0;
  const [wy, wm, wd] = weekRange.startStr.split("-").map(Number);
  const [, , wed] = weekRange.endStr.split("-").map(Number);
  for (let day = wd; day <= wed; day++) {
    const curDateStr = `${wy}-${String(wm).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
    weekActualHours += getWorkHoursForDate(curDateStr);
  }
  weekActualHours = Math.round(weekActualHours * 100) / 100;

  const weeklyMentor = calculatePerformanceMentor({
    period: "WEEKLY",
    actualHours: weekActualHours,
    calendarDays: weekElapsedDays || 1,
    asOfDateStr: todayStr,
    totalDays: weekTotalDays,
    remainingDays: weekRemainingDays,
    simulateDaysOff: options?.simulateWeeklyDaysOff,
  });

  // Calculate actual hours for month
  let monthActualHours = 0;
  const [my, mm, md] = monthRange.startStr.split("-").map(Number);
  const [, , med] = monthRange.endStr.split("-").map(Number);
  for (let day = md; day <= med; day++) {
    const curDateStr = `${my}-${String(mm).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
    monthActualHours += getWorkHoursForDate(curDateStr);
  }
  monthActualHours = Math.round(monthActualHours * 100) / 100;

  const monthlyMentor = calculatePerformanceMentor({
    period: "MONTHLY",
    actualHours: monthActualHours,
    calendarDays: monthElapsedDays || 1,
    asOfDateStr: todayStr,
    totalDays: monthTotalDays,
    remainingDays: monthRemainingDays,
    simulateDaysOff: options?.simulateMonthlyDaysOff,
  });

  return {
    weekly: weeklyMentor,
    monthly: monthlyMentor,
    asOfDateStr: todayStr,
  };
}
